import Image from "next/image";
import { site } from "@/lib/site";

/*
 * The only place logo files are referenced. To swap in Kevin's vector source,
 * replace the files in public/ (or change the paths and viewBox sizes here).
 * The SVGs are generated by `npm run logo` — see scripts/logo/generate.mjs.
 */
const logos = {
  horizontal: { src: "/logo-paidtospeak.svg", width: 931.65, height: 134 },
  stacked: { src: "/logo-paidtospeak-stacked.svg", width: 458.05, height: 277 },
} as const;

type LogoProps = {
  variant?: keyof typeof logos;
  className?: string;
  priority?: boolean;
};

export function Logo({ variant = "horizontal", className, priority }: LogoProps) {
  const { src, width, height } = logos[variant];
  return (
    <Image
      src={src}
      alt={site.plainName}
      width={Math.round(width)}
      height={height}
      priority={priority}
      className={className}
    />
  );
}
